export const add_linkage={
    "header":{
        "transactionID":"",
        "sourceApp":"",
        "priority":"",
        "ticketType":"",
        "originalDetails":{
            "sourceSystem":"",
            "contractState":"",
            "corporateReceptDate":"",
            "requestors":[
                {
               "firstName":"",
               "lastname":"",
               "email":""             
                }
            ],
            "LOB":[]
        }
        
    },
    "profile":{
        "masterProvID":"",
        "keyData":{
            "typeCode":"181",
            "typeCodeTxt":"Individual",
            "taxID":"",
            "specialityCd":"",
            "taxonomyCd":[]
        
        }
    },
    "providerAddress":[
        {
            "address":{
                "keyData":{
                    "typeCode":"",
                    "state":""
                }
            }
        }
    ]
}